@startuml

Користувач -> Контролер : Запит на вхід в аккаунт
Контролер -> Сервіс : Вхід в акаунт
Сервіс -> Репозиторій : Перевірка даних
Репозиторій -> Сервіс : Перевірка даних
Сервіс --> Контролер : Токен доступу

Користувач -> Контролер : Запит на реєстрацію
Контролер -> Сервіс : Реєстрація
Сервіс -> Репозиторій : Додати користувача
Сервіс --> Контролер : Токен доступу

Користувач -> Контролер : Запит на дані про мотоцикли
Контролер -> Сервіс : Отримати дані про мотоцикли
Сервіс -> Репозиторій : Отримати дані про мотоцикли
Репозиторій -> Сервіс : Дані про мотоцикли
Сервіс --> Контролер : Дані про мотоцикли
Контролер --> Користувач : Дані про мотоцикли

Користувач -> Контролер : Запит на дані про платіж
Контролер -> Сервіс : Отримати дані про платіж
Сервіс -> Репозиторій : Отримати дані про платіж
Репозиторій -> Сервіс : Дані про платіж
Сервіс --> Контролер : Дані про платіж
Контролер --> Користувач : Дані про платіж

Користувач -> Контролер : Запит на дані про оренду
Контролер -> Сервіс : Отримати дані про оренду
Сервіс -> Репозиторій : Отримати дані про оренду
Репозиторій -> Сервіс : Дані про оренду
Сервіс --> Контролер : Дані про оренду
Контролер --> Користувач : Дані про оренду

Користувач -> Контролер : Запит на дані про користувача
Контролер -> Сервіс : Отримати дані про користувача
Сервіс -> Репозиторій : Отримати дані про користувача
Репозиторій -> Сервіс : Дані про користувача
Сервіс --> Контролер : Дані про користувача
Контролер --> Користувач : Дані про користувача

@enduml
